name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        run: |
          sudo apt-get update && sudo apt-get install -y sed
          VERSION=$(sed -E -n 's/^version = \"(.*)"$/\1/p' Cargo.toml)
          [ "$GITHUB_REF_NAME" == "v$VERSION" ]
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
